### PR TITLE
Looking at ways to add kentik devices for disco

### LINKED ISSUE #421: FR: support using Kentik flow devices as part of the SNMP devices inventory
as a user, I would like to be able to use Kentik Flow devices as part of my SNMP devices inventory. I would like to be able to enable this option in the configuration file and additionally to provide the way to select subset of devices. 
The list of devices can be retrieved by Kentik APIv5 devices endpoint

The configuration can look something like this:
```
kentik:
    use_device_inventory: true  # default should be false
    device_matching:
        ip_address:        # list of CIDRs to match "device_snmp_ip" from 
            - 10.0.0.1/32
            - 172.16.1.0/24
        labels:     # list of device labels, matching "any"
            - dc_iad1
            - spine
            - leaf
```
As part of this, the device in ktranslate should have set the following two tags:
- kentik.device_id: <kentik_device_id_from_api >
- site: <device_site_name>

These devices should be merged with the list of devices which can be provided by other means (snmp configuration file), with the possible overlapping. I would consider device_name an device_ip as a way to correlate/merge devices configured on both sides.

**optional:**
I would also consider moving the configuration of the user credentials for Kentik's API under the "kentik" key.
```
kentikemail: ""
kentikapitoken: ""
kentikplan: 0
apibaseurl: https://api.kentik.com
```
to:
```
kentik:
    - user_email: ""
    - user_token: ""
    - plan: 0
    - api_url: "https://api.kentik.com"
```

### PR DESCRIPTION
**Pull request by i3149**
This will try to run disco on any kentik devices which are found if the kentik creds are provided. Test with:

```
 KENTIK_API_TOKEN=$TOKEN ./bin/ktranslate -kentik_email kproxy-agent+$COPANY_ID@kentik.com  -snmp snmp.yaml -snmp_discovery
```

Closes #421.

### CODE REVIEW

**Comment by i3149** [comment]
WIP -- gonna add some more features.

**Comment by i3149** [comment]
OK -- what do you think of this?

**Comment by dpajin-kentik** [comment]
I see these labels (these is also site associated)
```
{
    "device": {
        "id": "1171",
        "company_id": "1013",
        "device_name": "edge01_fra1",
        "device_type": "router",
        "device_status": "V",
        "device_description": "",
        "site": {
            "id": 1,
            "site_name": "fra1",
            "lat": 50.0968833,
            "lon": 8.6441701,
            "company_id": 1013
        },
...
        },
        "labels": [
            {
                "id": 3,
                "name": "edge",
                "description": null,
                "edate": "2018-11-02T12:29:12.431Z",
                "cdate": "2018-11-02T12:29:12.431Z",
                "user_id": null,
                "company_id": "1013",
                "color": "#2b3989",
                "order": null,
                "_pivot_device_id": "1171",
                "_pivot_label_id": "3"
            },
            {
                "id": 2,
                "name": "fra1",
                "description": null,
                "edate": "2018-11-01T15:02:02.707Z",
                "cdate": "2018-11-01T15:02:02.707Z",
                "user_id": null,
                "company_id": "1013",
                "color": "#63707D",
                "order": null,
                "_pivot_device_id": "1171",
                "_pivot_label_id": "2"
            },
            {
                "id": 4,
                "name": "juniper",
                "description": null,
                "edate": "2018-11-02T12:29:26.363Z",
                "cdate": "2018-11-02T12:29:26.363Z",
                "user_id": null,
                "company_id": "1013",
                "color": "#3c3294",
                "order": null,
                "_pivot_device_id": "1171",
                "_pivot_label_id": "4"
            }
        ],
```

**Comment by dpajin-kentik** [comment]
@i3149, I have additional requirement which I haven't mention in the issue - would you be able to add to all discovered devices the following tag `tags.kentik.device_id` which would contain Kentik's  device ID number, which would help correlating data back at the ingest?

**Comment by i3149** [comment]
@dpajin-kentik  -- can you share the API you're using to get this info?

**Review by ehazlett — APPROVED** [review]

**Review by ehazlett — DISMISSED** [review]

**Comment by i3149** [comment]
OK, I found the API. Now can filter on IP and Label. 

Example section: 

 ```  
kentik:
    use_device_inventory: true
    device_matching:
      ip_address:
      - 68.183.120.0/24
      labels:
      - foo
```

**Comment by dpajin-kentik** [comment]
@ehazlett @i3149, I have tested it briefly and works good for me so far.

**Review by ehazlett — APPROVED** [review]

**Pull request merged**
