### PR TITLE
elasticsearch: include more geo data

### PR DESCRIPTION
**Pull request by ehazlett**
This adds more geolocation fields to the elasticsearch fomatter.

### CODE REVIEW

**Review by i3149 — APPROVED** [review]
This passes these fields regardless, even if they are not set. But if they are set, the fields should still be going through, not just getting dropped right?

**Comment by ehazlett** [comment]
> This passes these fields regardless, even if they are not set. But if they are set, the fields should still be going through, not just getting dropped right?

Correct.  Should I check if they are empty or leave them as passing?  I'm not sure what convention we use for other formatters and what's preferred.

**Comment by ehazlett** [comment]
Ah I just saw `// Always pass along even if 0` -- should we leave it to include the fields then?

**Comment by i3149** [comment]
Eah, can't hurt to have.

**Pull request merged**
